name: Deploy to Azure Kubernetes Service

on:
  push:
    branches:
      - main

env:
  RESOURCE_GROUP: rg-cicdpipeline
  AKS_CLUSTER: aks-cicdpipeline
  ACR_NAME: acrcicd
  DOCKER_IMAGE: python-imdb
  HELM_CHART: pythonchart

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Azure CLI
      uses: azure/setup-azure-cli@v1
      with:
        scope: "subscription"
        azcliversion: "latest"

    - name: Create resource group
      run: az group create --name $RESOURCE_GROUP --location eastus

    - name: Create AKS cluster
      run: |
        az aks create --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER --node-count 1 --generate-ssh-keys
        az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER

    - name: Login to ACR
      run: az acr login --name $ACR_NAME

    - name: Build and push Docker image
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker build -t $DOCKER_IMAGE .
        docker tag $DOCKER_IMAGE $ACR_NAME.azurecr.io/$DOCKER_IMAGE
        docker push $ACR_NAME.azurecr.io/$DOCKER_IMAGE

    - name: Deploy with Helm
      uses: azure/helm@v1.2.3
      with:
        command: upgrade
        arguments: --install $HELM_CHART ./helm-chart
        namespace: default
        set_values: |
          image.repository=$ACR_NAME.azurecr.io/$DOCKER_IMAGE
